#include "plugin/ui/main_window.h"

#include <cstdio>

#include "plugin/announcer.h"
#include "plugin/xa_log.h"

namespace xa {
namespace {

const char* phaseTitle(core::Phase phase) {
    switch (phase) {
        case core::Phase::Preflight: return "Подготовка";
        case core::Phase::Boarding:  return "Посадка";
        case core::Phase::Pushback:  return "Двери и брифинг";
        case core::Phase::Takeoff:   return "Взлёт";
        case core::Phase::Climb:     return "Набор";
        case core::Phase::Cruise:    return "Эшелон";
        case core::Phase::Descent:   return "Снижение";
        case core::Phase::Approach:  return "Заход";
        case core::Phase::TaxiIn:    return "После посадки";
        case core::Phase::Disembark: return "Высадка";
    }
    return "-";
}

}  // namespace

MainWindow::MainWindow(Announcer* announcer)
    : XpImguiWindow(620, 520, "X-Announcer 2"), announcer_(announcer) {}

void MainWindow::buildUi() {
    if (announcer_ == nullptr) {
        ImGui::TextUnformatted("Плагин не запустился — смотрите Log.txt.");
        return;
    }
    if (ImGui::BeginTabBar("tabs")) {
        if (ImGui::BeginTabItem("Рейс")) {
            drawFlightTab();
            ImGui::EndTabItem();
        }
        if (ImGui::BeginTabItem("Библиотека")) {
            drawLibraryTab();
            ImGui::EndTabItem();
        }
        if (ImGui::BeginTabItem("Журнал")) {
            drawLogTab();
            ImGui::EndTabItem();
        }
        ImGui::EndTabBar();
    }
}

void MainWindow::drawFlightTab() {
    core::Engine& engine = announcer_->engine();
    const core::Snapshot& s = announcer_->lastSnapshot();

    ImGui::Text("Фаза: %s", phaseTitle(engine.phase()));
    ImGui::SameLine();
    ImGui::TextDisabled("(%s)", core::phaseId(engine.phase()));

    // What the machine is waiting for. This list is generated by the same code
    // the offline bench cross-checks against the state machine, so it cannot
    // quietly start lying about what is holding the flight up.
    ImGui::Spacing();
    ImGui::Text("Дальше — «%s», ждём:", engine.nextPhaseLabel(s).c_str());
    for (const core::Condition& c : engine.phaseConditions(s)) {
        if (c.met) {
            ImGui::TextColored(ImVec4(0.45f, 0.80f, 0.45f, 1.0f), "  [x] %s", c.label.c_str());
        } else {
            ImGui::TextColored(ImVec4(0.90f, 0.75f, 0.35f, 1.0f), "  [ ] %s", c.label.c_str());
        }
        if (!c.value.empty()) {
            ImGui::SameLine();
            ImGui::TextDisabled("— %s", c.value.c_str());
        }
    }

    ImGui::Separator();
    if (announcer_->player().announcementActive()) {
        ImGui::Text("Играет: %s", announcer_->player().announcementEvent().c_str());
    } else {
        ImGui::TextDisabled("Играет: тишина");
    }
    ImGui::Text("В очереди: %zu", engine.queueSize());
    if (engine.musicPlaying()) {
        ImGui::Text("Фон: %s", engine.musicEvent().c_str());
    }

    ImGui::Separator();
    ImGui::TextDisabled("Что видит плагин");
    ImGui::Text("на земле: %s   двигателей: %d   маяк: %s",
                s.onGround ? "да" : "нет", s.enginesRunning, s.beacon ? "вкл" : "выкл");
    ImGui::Text("высота: %.0f фт   над землёй: %.0f фт   верт.: %.0f фт/мин",
                s.altFt, s.aglFt, s.vsFpm);
    ImGui::Text("скорость: %.0f уз   местный час: %d   %s",
                s.gsKt, s.localHour, s.isDark() ? "темно" : "светло");
    const char* belt = s.seatbelt == core::Tri::Unknown ? "борт его не публикует"
                                                        : (s.seatbelt == core::Tri::On ? "горит" : "погашено");
    ImGui::Text("табло ремней: %s", belt);
    if (announcer_->simState().seatbeltDataref()[0] != '\0') {
        ImGui::TextDisabled("  %s", announcer_->simState().seatbeltDataref());
    }
}

void MainWindow::drawLibraryTab() {
    FileSoundLibrary& library = announcer_->library();
    ImGui::TextWrapped("Папка: %s", library.root().c_str());
    ImGui::Text("Паков: %zu, в выбранном объявлений: %d",
                library.packs().size(), library.eventCount());
    ImGui::Separator();

    // Airline detection from the livery is not ported yet, so the pack is picked
    // by hand here. This is temporary and the panel says so rather than leaving
    // the wrong pack looking deliberate.
    ImGui::TextDisabled("Определение авиакомпании по ливрее ещё не перенесено — пак выбирается вручную.");
    for (const std::string& name : library.packs()) {
        const bool selected = name == library.pack();
        if (ImGui::RadioButton(name.c_str(), selected) && !selected) {
            library.selectPack(name);
        }
    }

    ImGui::Separator();
    ImGui::TextDisabled("Проверка звука без полёта:");
    static const char* const kProbeEvents[] = {"BoardingWelcome", "SafetyBriefing",
                                               "CrewSeatsTakeoff", "AfterLanding"};
    for (const char* event : kProbeEvents) {
        const bool available = library.has(event);
        ImGui::BeginDisabled(!available);
        if (ImGui::Button(event)) {
            announcer_->player().playAnnouncement(event, library.pathFor(event), announcer_->volume);
            log("UI: ручное воспроизведение %s", event);
        }
        ImGui::EndDisabled();
        ImGui::SameLine();
        if (available) {
            ImGui::TextDisabled("%.1f с", library.duration(event));
        } else {
            ImGui::TextDisabled("нет в паке");
        }
    }
    if (ImGui::Button("Стоп")) {
        announcer_->player().stopAnnouncement();
    }
    ImGui::SameLine();
    if (ImGui::Button("Пересканировать")) {
        library.scan(library.root());
    }
}

void MainWindow::drawLogTab() {
    if (ImGui::BeginChild("log", ImVec2(0.0f, 0.0f), ImGuiChildFlags_Borders)) {
        for (const std::string& line : logTail(200)) {
            ImGui::TextUnformatted(line.c_str());
        }
    }
    ImGui::EndChild();
}

}  // namespace xa
