#!/usr/bin/env python3
"""Convert 1.x's airlines.lua into the flat table the C++ core reads.

Source: OpenFlights airline database, Open Database License (ODbL). Only rows
with a valid three-letter ICAO code are kept, exactly as 1.x kept them - the two
implementations must index the same carriers or the detection comparison between
them proves nothing.

    python scripts/make_airlines.py [path-to-airlines.lua]

Output: assets/airlines.txt, one "ICAO<TAB>Name" per line, sorted by ICAO so the
file is stable in diffs.
"""

import os
import re
import sys

DEFAULT_SOURCE = r"D:\claude2\x-announcer\x_announcer\airlines.lua"

# ["AAA"]={n="Ansett Australia",c="ANSETT",i="AN"},
ROW = re.compile(r'\["([A-Z0-9]{3})"\]\s*=\s*\{n="((?:[^"\\]|\\.)*)"')


def main() -> int:
    source = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_SOURCE
    here = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    target = os.path.join(here, "assets", "airlines.txt")

    with open(source, encoding="utf-8") as f:
        text = f.read()

    rows = {}
    for icao, name in ROW.findall(text):
        name = name.replace('\\"', '"').replace("\\\\", "\\")
        # First row wins, matching the Lua table where a duplicate key would
        # simply have been overwritten at load time by the last one - there are
        # no duplicate keys in a Lua table literal, so this cannot differ.
        rows.setdefault(icao, name)

    os.makedirs(os.path.dirname(target), exist_ok=True)
    with open(target, "w", encoding="utf-8", newline="\n") as f:
        f.write("# ICAO<TAB>Name. Generated by scripts/make_airlines.py - do not edit.\n")
        f.write("# Source: OpenFlights airline database (https://openflights.org/data.html),\n")
        f.write("# Open Database License (ODbL).\n")
        for icao in sorted(rows):
            f.write(f"{icao}\t{rows[icao]}\n")

    print(f"{len(rows)} airlines -> {target}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
